# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ef8a711fb8eb777d80f4a5550e53fb20c36596b929fc43a68aa4edb7d6b4469464d5927f27e825648a80c2ba4f8b2b7733582486b738931fbbec432a5d7accc

test:
  secret_key_base: 8f1e7d6855e64df52c3f7190b063049d9d744eea96bbda039e03cf2e5580e76e3ebc28cb28f6eecb276abf34d261e155e68aa21ae07feb82fe4d9757561b0929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
